version: '3.7'

services:

  dev:
    container_name: react-test-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    command: npm start

  test:
    container_name: react-test
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - CI=true
    command: yarn test -u